# Generated by Django 6.0.4 on 2026-06-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('cod', 'COD'), ('getpay', 'GetPay')], default='cod', max_length=20),
        ),
    ]
