# Generated by Django 6.0.4 on 2026-05-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_subtotal_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('cod', 'COD')], default='cod', max_length=20),
        ),
    ]
