# Generated by Django 6.0.4 on 2026-05-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_shipping_address_order_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
