# Generated by Django 6.0.4 on 2026-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.CharField(blank=True),
        ),
    ]
