# Generated by Django 6.0.4 on 2026-05-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_profile_address_profile_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_spend',
        ),
    ]
