# Generated by Django 6.0.4 on 2026-08-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_user_isverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
