# Generated by Django 6.0.4 on 2026-08-12 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_suggestions'),
        ('product', '0010_alter_atomizer_description_alter_atomizer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('decant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests', to='product.decant')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests', to='product.perfume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
