# Generated by Django 6.0.4 on 2026-08-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_stocknotificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.CharField(choices=[('3ml', '3ml Atomizer'), ('5ml', '5ml Atomizer'), ('20ml', '20ml Atomizer')], max_length=20)),
                ('sent', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_claims', to='people.profile')),
            ],
            options={
                'unique_together': {('profile', 'gift')},
            },
        ),
    ]
