# Generated by Django 6.0.4 on 2026-05-11 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atomizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=100)),
                ('is_premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtomizerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colors', models.CharField(blank=True, max_length=50)),
                ('atomizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.atomizer')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Perfume', 'perfume'), ('Attar', 'attar')], default='perfume', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_seasonal_pick', models.BooleanField(default=False)),
                ('is_restocked', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('family', models.ManyToManyField(to='product.family')),
            ],
        ),
        migrations.CreateModel(
            name='Longevity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, help_text='Enter a value from 0 to 24, representing the number of hours the perfume lasts.', validators=[django.core.validators.MaxValueValidator(24)])),
                ('perfume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='longevity', to='product.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='Decant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='perfume_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='PerfumeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N/A', 'N/A'), ('top', 'Top'), ('middle', 'Middle'), ('base', 'Base')], default='N/A', max_length=10)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.notes')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.perfume')),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='note',
            field=models.ManyToManyField(blank=True, through='product.PerfumeNote', to='product.notes'),
        ),
        migrations.CreateModel(
            name='Sillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, help_text='Enter a value from 0 to 10, where 0 means no sillage and 10 means very strong sillage.', validators=[django.core.validators.MaxValueValidator(10)])),
                ('perfume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sillage', to='product.perfume')),
            ],
        ),
        migrations.CreateModel(
            name='Thrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_juice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thrift_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thrifts', to='product.perfume')),
            ],
        ),
    ]
