# Generated by Django 6.0.4 on 2026-05-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_atomizervariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomizervariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='atomizer_images/'),
        ),
    ]
