# Generated by Django 6.0.4 on 2026-05-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_atomizervariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='thrift',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
