# Generated by Django 6.0.4 on 2026-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_thrift_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomizervariant',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decant',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfume',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thrift',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
