# Generated by Django 6.0.4 on 2026-06-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_atomizervariant_reserved_decant_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumeimage',
            name='image',
            field=models.ImageField(upload_to='Perfumes/'),
        ),
    ]
