# Generated by Django 6.0.4 on 2026-06-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_perfumeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='collection',
            field=models.CharField(blank=True, choices=[('niche', 'Niche'), ('designer', 'Designer'), ('middle_eastern', 'Middle Eastern'), ('in_house', 'In House')], db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='full_bottle_size',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
