# Generated by Django 6.0.4 on 2026-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_perfume_collection_perfume_full_bottle_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasalStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='nasal_strip_images/')),
            ],
        ),
    ]
