# Generated by Django 6.0.4 on 2026-08-09 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_nasalstrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThriftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thrift_images/')),
                ('thrift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.thrift')),
            ],
        ),
    ]
