# Generated by Django 6.0.4 on 2026-08-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_thriftimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomizer',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='atomizer',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
