# Generated by Django 6.0.4 on 2026-08-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_atomizer_description_alter_atomizer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atomizervariant',
            options={'ordering': ['size']},
        ),
        migrations.RenameField(
            model_name='atomizervariant',
            old_name='reserved',
            new_name='available_stock',
        ),
        migrations.RemoveField(
            model_name='atomizervariant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='atomizervariant',
            name='stock',
        ),
        migrations.AlterField(
            model_name='atomizer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='atomizer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='atomizervariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='atomizervariant',
            name='size',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='AtomizerVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='atomizer-images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.atomizervariant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
