# Generated by Django 6.0.4 on 2026-08-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_atomizervariant_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atomizervariant',
            old_name='available_stock',
            new_name='reserved',
        ),
        migrations.AddField(
            model_name='atomizervariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
