# Generated by Django 6.0.4 on 2026-04-30 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_perfume_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atomizer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='atomizer',
            name='size',
        ),
        migrations.AddField(
            model_name='atomizer',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atomizer',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AtomizerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colors', models.CharField(blank=True, max_length=50)),
                ('atomizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.atomizer')),
            ],
        ),
    ]
