# Generated by Django 6.0.4 on 2026-04-30 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_atomizer_price_remove_atomizer_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomizer',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
