# Generated by Django 6.0.4 on 2026-05-02 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_atomizer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_juice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thrift_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.perfume')),
            ],
        ),
    ]
