# Generated by Django 6.0.4 on 2026-05-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_thrift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thrift',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thrifts', to='product.perfume'),
        ),
    ]
