# Generated by Django 6.0.4 on 2026-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_thrift_perfume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='price',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='stock',
        ),
        migrations.AddField(
            model_name='decant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
