# Generated by Django 6.0.4 on 2026-05-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_perfume_price_remove_perfume_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='perfume',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
